Magenta_S/Magenta_S/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magenta_S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Colors = new HashSet<Color>();
            this.Posts = new HashSet<Post>();
            this.Sizes = new HashSet<Size>();
            this.Buys = new HashSet<Buy>();
        }
    
        public int Idproduct { get; set; }
        public int Idu { get; set; }
        public string Type { get; set; }
        public string Genderoftype { get; set; }
        public string Quality { get; set; }
        public string Season { get; set; }
        public string Company { get; set; }
        public string Description { get; set; }
        public string Meadin { get; set; }
        public int Price { get; set; }
        public int count { get; set; }
        public bool Ok { get; set; }
        public string image { get; set; }
        public System.DateTime date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Color> Colors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Size> Sizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy> Buys { get; set; }
    }
}

Magenta_S/Magenta_S/Controllers/BaysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Magenta_S.Models;
using System.Data.Entity;
using System.Threading.Tasks;

namespace Magenta_S.Controllers
{
    public class BaysController : Controller
    {
        private readonly magentadb _magentaDataContext = new magentadb();

        public ActionResult Carta()
        {
            Bay_Product product = new Bay_Product();

            product.Idu = (int)Session["iduser"];

            User user = _magentaDataContext.Users.FirstOrDefault(x => x.Idu == product.Idu);
            product.idseesion = user.Idc;

            return View(product);
        }

        [HttpPost]
        public ActionResult Carta(string Sizee, string ColorP, int Count, int Idproduct, bool Ok, int Idu, int checkp)
        {
            Buy buy = new Buy();

            buy.Idproduct = Idproduct;
            buy.Idu = Idu;
            buy.Ok = Ok;
            buy.ColorP = ColorP;
            buy.Sizee = Sizee;
            buy.bill = null;
            buy.Count = Count;
            buy.checkp = checkp;

            _magentaDataContext.Entry(buy).State = EntityState.Deleted;
            _magentaDataContext.SaveChanges();

            return RedirectToAction("Carta");
        }

        [HttpPost]
        public ActionResult buy(string phone, string address, int Idu)
        {
            Bill bill = new Bill();

            bill.Idu = Idu;
            bill.Newphone = phone;
            bill.Newplace = address;
            bill.date = DateTime.Now;

            _magentaDataContext.Bills.Add(bill);
            _magentaDataContext.SaveChanges();

            List<Buy> listbue = _magentaDataContext.Buys.Where(x => x.Idu == Idu && x.Ok == false)
                                                        .ToList();

            foreach (var item in listbue)
            {
                item.Ok = true;
                item.Bill1 = bill;

                _magentaDataContext.Entry(item).State = EntityState.Modified;

            }

            _magentaDataContext.SaveChanges();

            List<Buy> listbuy = _magentaDataContext.Buys.Where(x => x.bill == bill.Idbill).ToList();

            double totalprice = 0;
            int count = 0;

            foreach (var item in listbuy)
            {
                totalprice += item.Product.Price * item.Count * 1.05;
                count += item.Count;

            }

            bill.Totalprice = (int)totalprice;

            _magentaDataContext.Entry(bill).State = EntityState.Modified;
            _magentaDataContext.SaveChanges();

            User user = _magentaDataContext.Users.Where(x => x.Idu == Idu).Single();
            user.CountProduct = count;

            _magentaDataContext.Entry(user).State = EntityState.Modified;
            _magentaDataContext.SaveChanges();

            foreach (var item in listbuy)
            {
                Product product = item.Product;
                product.count = product.count - item.Count;

                _magentaDataContext.Entry(product).State = EntityState.Modified;

            }

            _magentaDataContext.SaveChanges();

            if (user.Idc == 2)
            {
                return RedirectToAction("HomeCustomer", "Home");
            }

            return RedirectToAction("HomeDealer", "Home");
        }

        public ActionResult My_Buy(int id)
        {
            int iduser = (int)Session["iduser"];

            User user = _magentaDataContext.Users.Where(x => x.Idu == id).Single();
            my_buy my_Buy = new my_buy();

            my_Buy.idu = id;
            my_Buy.idseesion = user.Idc;

            return View(my_Buy);
        }

        public async Task<ActionResult> AI_Suggestions()
        {
            int iduser = (int)Session["iduser"];

            User user = _magentaDataContext.Users.FirstOrDefault(x => x.Idu == iduser);

            my_buy my_Buy = new my_buy();

            my_Buy.idseesion = user.Idc;
            my_Buy.TextAPI = await my_Buy.GetProductSuggestionsForSeller();

            return View(my_Buy);
        }
    }
}

Magenta_S/Magenta_S/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;
using System.IO;
using Magenta_S.Models;
using System.Data.Entity;
using System.Net.Http;
using Newtonsoft.Json;

namespace Magenta_S.Controllers
{
    public class ProductController : Controller
    {
        private readonly magentadb _magentaDataContext = new magentadb();

        private string CheckPhoto(HttpPostedFileBase upload)
        {
            string apiKey = Environment.GetEnvironmentVariable("API_KEY");
            string url = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={apiKey}";

            byte[] imageBytes = new byte[upload.ContentLength];
            upload.InputStream.Read(imageBytes, 0, upload.ContentLength);
            string base64Image = Convert.ToBase64String(imageBytes);

            var parts = new List<object>{new
                     {
                     text = "If the image contains inappropriate scenes, nudity, or pictures of people on the beach in inappropriate clothing, answer me with \"yes.\" Otherwise, answer me with \"no\" only, nothing else."
                    },
                 new
                    {
                 inline_data = new
                     {
                    mime_type = upload.ContentType,
                     data = base64Image
                 }
                    }
                 };

            var requestBody = new
            {
                contents = new[]
                {
                new
                {
                    role = "user",
                    parts = parts
                }
            }
            };

            using (var client = new HttpClient())
            {
                var content = new StringContent(JsonConvert.SerializeObject(requestBody), Encoding.UTF8, "application/json");
                var response = client.PostAsync(url, content).Result;

                if (response.IsSuccessStatusCode)
                {
                    var responseContent = response.Content.ReadAsStringAsync().Result;

                    if (responseContent.Contains("yes"))
                    {
                        return "yes";
                    }
                }
                else
                {
                    return "no";
                }
            }
            return "Error";
        }

        public ActionResult Add_Product()
        {

            ProductA product = new ProductA();

            product.dataforSelectsize();
            product.dataforSelectcolor();

            return View(product);
        }

        [HttpPost]
        public ActionResult Add_Product(ProductA a, HttpPostedFileBase Upload)
        {
            if (Upload == null)
            {
                ModelState.AddModelError("imageu", " Please Enter image ");
                return View();
            }

            if (CheckPhoto(Upload) == "yes")
            {
                ModelState.AddModelError("imageu", "الصورة تحتوي على مشاهد غير لائقة.");
                return View();
            }

            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/imageproduct"), Upload.FileName);
                Upload.SaveAs(path);

                ProductA productA = new ProductA();
                Product product = productA.getproduct(a);

                product.image = Upload.FileName;

                bool checkforsize = false;
                bool checkforcolor = false;

                foreach (var item in a.Selectcolor)
                {
                    if (item.Selected)
                    {
                        checkforcolor = true;

                        Color color = new Color();
                        color.ColorP = item.Value;

                        product.Colors.Add(color);
                    }
                }
                foreach (var item in a.Selectsize)
                {
                    if (item.Selected)
                    {
                        checkforsize = true;

                        Size size = new Size();
                        size.size1 = item.Value;

                        product.Sizes.Add(size);

                    }
                }
                if (checkforsize == false)
                {
                    ModelState.AddModelError("checks", " Please Enter Size ");

                    productA.dataforSelectsize();

                    productA.dataforSelectcolor();

                    return View(productA);

                }
                if (checkforcolor == false)
                {

                    ModelState.AddModelError("checkc", " Please Enter Color  ");
                    productA.dataforSelectsize();

                    productA.dataforSelectcolor();

                    return View(productA);

                }
                product.Idu = (int)(Session["iduser"]);

                _magentaDataContext.Products.Add(product);
                _magentaDataContext.SaveChanges();

                return RedirectToAction("HomeDealer", "Home");
            }
            return View();
        }

        public ActionResult My_Product()
        {
            ProductA product = new ProductA();
            product.Idu = (int)Session["iduser"];

            return View(product);
        }

        [HttpPost]
        [ActionName("My_Product")]
        public ActionResult My_Products(int Idproduct)
        {
            Product product = _magentaDataContext.Products.FirstOrDefault(x => x.Idproduct == Idproduct);

            try
            {
                _magentaDataContext.Products.Remove(product);
                _magentaDataContext.SaveChanges();
            }
            catch
            {
                product.Ok = false;
                _magentaDataContext.Entry(product).State = EntityState.Modified;
                _magentaDataContext.SaveChanges();
            }

            return RedirectToAction("My_Product");

        }

        [HttpGet]
        public ActionResult Modification(int Idproduct)
        {
            int idu = (int)Session["iduser"];

            ProductA product = new ProductA();
            product.UpdateProduct(Idproduct);

            if (product.Idu != idu)
            {
                throw new HttpException(404, "Bad Request");

            }

            product.dataforSelectsize();
            product.dataforSelectcolor();

            return View(product);
        }

        [HttpPost]
        public ActionResult Modification(ProductA p)
        {
            bool checkforsize = false;
            bool checkforcolor = false;

            ProductA productA = new ProductA();
            Product product = productA.UpdateProduct(p);

            foreach (var item in p.Selectcolor)
            {
                if (item.Selected)
                {
                    checkforsize = true;

                    Color color = new Color();

                    color.ColorP = item.Value;
                    color.Product = product;
                    color.Idprodact = product.Idproduct;

                    product.Colors.Add(color);
                }
            }

            foreach (var item in p.Selectsize)
            {
                if (item.Selected)
                {
                    checkforcolor = true;

                    Size size = new Size();

                    size.size1 = item.Value;
                    size.idproduct = product.Idproduct;
                    size.Product = product;

                    product.Sizes.Add(size);

                }
            }

            if (checkforsize == false)
            {
                ModelState.AddModelError("checks", " Please Enter Size ");

                productA.UpdateProduct(p.Idproduct);

                productA.dataforSelectsize();
                productA.dataforSelectcolor();

                return View(productA);

            }
            if (checkforcolor == false)
            {
                ModelState.AddModelError("checkc", " Please Enter Color  ");

                productA.UpdateProduct(p.Idproduct);

                productA.dataforSelectsize();
                productA.dataforSelectcolor();

                return View(productA);
            }

            _magentaDataContext.Entry(product).State = EntityState.Modified;
            _magentaDataContext.SaveChanges();

            _magentaDataContext.Sizes.RemoveRange(_magentaDataContext.Sizes.Where(c => c.idproduct == product.Idproduct));
            _magentaDataContext.SaveChanges();

            _magentaDataContext.Sizes.AddRange(product.Sizes).Where(x => x.idproduct == product.Idproduct);
            _magentaDataContext.SaveChanges();

            _magentaDataContext.Colors.RemoveRange(_magentaDataContext.Colors.Where(c => c.Idprodact == product.Idproduct));
            _magentaDataContext.SaveChanges();

            _magentaDataContext.Colors.AddRange(product.Colors).Where(x => x.Idprodact == product.Idproduct);
            _magentaDataContext.SaveChanges();


            return RedirectToAction("HomeDealer", "Home");
        }

        [HttpGet]
        public ActionResult Offer(int Idproduct)
        {
            Product p = _magentaDataContext.Products.FirstOrDefault(x => x.Idproduct == Idproduct);

            return View(p);
        }

        [HttpPost]
        public ActionResult Offer()
        {
            return View();
        }

        public ActionResult All_Product()
        {
            return View();
        }

        public ActionResult Products_For_Admin()
        {
            return View();
        }

    }
}

Magenta_S/Magenta_S/Views/Product/My_Product.cshtml
@model Magenta_S.Models.ProductA
@{
    Layout = null;
}

<<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="">

    <link href="~/Content/Home/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Home/fontawesome/js/all.css" rel="stylesheet" />
    <link href="~/Content/My_Product/style.css" rel="stylesheet" />
    <link href="~/Content/Home/css/dosis.css" rel="stylesheet" />
    <link href="~/Content/Home/css/roboto.css" rel="stylesheet" />
    <style>
        .item.header {
            background-image: url('../../../Image/Home/homeimg.jpg');
        }

        .update {
            margin-top: -91px;
        }

        .bu {
            height: 50px;
        }

        .navbar-header .in {
            margin-left: -5px;
            height: 50px;
            width: 280px;
        }
    </style>

</head>
<body>

    <!-- HEADER =============================-->
    <header class="item header margin-top-0">
        <div class="wrapper">
            <nav role="navigation" class="navbar navbar-white navbar-embossed navbar-lg navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
                            <i class="fa fa-bars"></i>
                            <span class="sr-only">Toggle navigation</span>

                        </button>
                        <a   href='@Url.Action("HomeDealer", "Home")' class="navbar-brand brand"><img src="~/Image/logo.png" width="110" height="110" style="margin-top: -23px;" /> </a>



                        <ul class="nav navbar-nav navbar-left">

                        </ul>
                        <button class="bu"> SERACH </button>
                        <input type="search" class="in">
                    </div>
                    <div id="navbar-collapse-02" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="propClone mb"><a href='@Url.Action("UpdateAccount", "Account",new {@id=Model.Idu })'><i class="fa fa-user fa-3x"></i></a></li>
                            <li class="propClone mb"><a  href='@Url.Action("Carta", "Bays")'><i class="fa fa-shopping-cart fa-3x"></i></a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <div class="text-pageheader">
                            <div class="subtext-image" data-scrollreveal="enter bottom over 1.7s after 0.1s">
                                My Products
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </header>

    <!-- CONTENT =============================-->
    <!--navbar-->
    <!--start allllllllll 99999999999999999999999-->
    <div class="container update">
        <div class="row">
            @{  bool s = false;}
            @foreach (var item in Model.getallproduct)
            {
                using (@Html.BeginForm(new { @idproduct = item.Idproduct }))
                {
                    s = true;
                    @*<select class="form-select s1">
                            <optgroup label="TYPE OF PRODUCT"></    optgroup>
                            <option selected class="bo">ِAll</option>
                            <option value="1">Tshirt</option>
                            <option value="2">Address</option>
                            <option value="3">Shoes</option>
                            <option value="3">Shirt</option>
                            <option value="3">Trousers</option>
                            <option value="3">Jeans</option>
                        </select>
                        <select class="form-select">
                            <optgroup label="GENDER OF PRODUCT"></optgroup>
                            <option selected>All</option>
                            <option value="1">Male</option>
                            <option value="2">Female</option>
                        </select>
                        <select class="form-select">
                            <optgroup label="Quality"></optgroup>
                            <option selected>All</option>
                            <option value="1">Cotton</option>
                            <option value="2">Wool</option>
                            <option value="3">WaterProof</option>
                        </select>*@






                    <!-- /.productbox -->
                    <div class="col-md-4">
                        <div class="productbox">
                            <div class="fadeshop">
                                <div class="captionshop text-center" style="display: none;">
                                    <h3>@item.Quality</h3>
                                    <p>
                                        This is a short excerpt to generally describe what the item is about.
                                    </p>
                                    <p>
                                        <a href="#" class="learn-more detailslearn" data-toggle="modal" data-target="#@item.Idproduct"><i class="fa fa-link"></i> Details</a>
                                    </p>
                                </div>
                                <span class="maxproduct">  <img src="~/imageproduct/@Url.Content(item.image)" height="312" width="500" />  </span>
                            </div>
                            <div class="product-details">

                                <h1>@item.Type</h1>

                                <span class="price">
                                    <span class="edd_price newprice"> @item.Price </span>
                                    @{ int cp = item.Idproduct + 2; }
                                    <a class="btn btn-danger btnd" data-toggle="modal" data-target="#@cp" name="ss">Delete This Product</a><br>
                                    @*<a href='@Url.Action("Carta", "Bays")'>*@

                                    <button type="button" class="btn btn-primary btnu" value="update" onclick="window.location.href='@Url.Action("Modification", "Product", new { @Idproduct = item.Idproduct })'">Product Modification</button><br>
                                </span>
                            </div>
                        </div>
                    </div>




    <!-- Modals =============================-->

                    <div class="modal fade" tabindex="-1" role="dialog" id="@item.Idproduct">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title text-center">Details Of Product</h4>
                                </div>
                                <div class="modal-body text-center">
                                    <label>Type Of Product : </label> <span>@item.Type</span><br>
                                    <label>Gender Of Type : </label> <span>@item.Genderoftype</span><br>
                                    <label>Quality Of Product : </label> <span>@item.Quality</span><br>
                                    <label>Size Of Product : </label> <span>
                                        @foreach (var x in item.Sizes)
                                        {

                                            <text>    </text>   @x.size1;   <text> ,  </text>

}

                                    </span><br>
                                    <label>Made in : </label> <span>@item.Meadin</span><br>
                                    <label>Color Of Product : </label> <span>
                                        @foreach (var i in item.Colors)
                                        {
                                            <text>  </text>
                                            @i.ColorP}
                                    </span><br>
                                    <label>Description : </label> <span>@item.Description</span><br>

                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->



                    <div class="modal fade" tabindex="-1" role="dialog" id="@cp">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">

                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                                    <h4 class="modal-title text-center">Are you sure to delete this product ?</h4>
                                </div>
                                <div class="modal-body text-center">

                                    <button type="submit" class="btn btn-danger" value="@item.Idproduct">DELETE</button>

                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                }
            }
        </div>
    </div>
    @if (s == false)
    {
    <section class="content-block" style="background-color:#00bba7;">
        <div class="container text-center">
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    <div class="subtext-image" data-scrollreveal="enter bottom over 1.7s after 0.1s">
                        <h1 class="callactiontitle">
                            There is No products for you
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </section>
    }
    <!--end alllllll 999999999999999999999999999-->
    <!-- FOOTER =============================-->
    <div class="footer text-center">
        <div class="container">
            <div class="row">
                <p class="footernote">
                    Connect with Magenta
                </p>
                <ul class="social-iconsfooter">
                    <li><a href="#"><i class="fa fa-phone" style="margin-top:25px;"></i></a></li>
                    <li><a href="#"><i class="fab fa-facebook-f" style="margin-top:25px;"></i></a></li>
                    <li><a href="#"><i class="fab fa-twitter" style="margin-top:25px;"></i></a></li>
                    <li><a href="#"><i class="fab fa-google-plus-g" style="margin-top:25px;"></i></a></li>
                    <li><a href="#"><i class="fab fa-pinterest-p" style="margin-top:25px;"></i></a></li>
                </ul>
                <p>
                    &copy; 2021 Magenta<br />

                </p>
            </div>
        </div>
    </div>

    <!-- Load JS here for greater good =============================-->
    <script src="~/Scripts/Home/jquery-.js"></script>
    <script src="~/Scripts/Home/bootstrap.min.js"></script>
    <script src="~/Scripts/Home/anim.js"></script>

    <script>
//----HOVER CAPTION---//
jQuery(document).ready(function ($) {
	$('.fadeshop').hover(
		function(){
			$(this).find('.captionshop').fadeIn(150);
		},
		function(){
			$(this).find('.captionshop').fadeOut(150);
		}
	);
});
    </script>
</body>
</html>