Magenta_S/Magenta_S/Controllers/ConrolPanelDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Magenta_S.Models;
using System.Data.Entity;

namespace Magenta_S.Controllers
{
    public class ConrolPanelDController : Controller
    {
        private readonly magentadb _magentaDataContext = new magentadb();

        private User GetUserByID(int ID)
        {
            return _magentaDataContext.Users.FirstOrDefault(x => x.Idu == ID);
        }

        public ActionResult ConrolPanelD()
        {
            return View();
        }

        public ActionResult Dealers_Reviews()
        {
            List<User> user = _magentaDataContext.Users.Where(x => x.Idc == 3 && x.Password != "unlockmagenta")
                                                       .ToList();
            return View(user);
        }

        [HttpPost]
        public ActionResult Dealers_Reviews(int id, string but)
        {
            if (but == "delete")
            {
                User user = GetUserByID(id);
                try
                {
                    _magentaDataContext.Users.Remove(user);
                    _magentaDataContext.SaveChanges();

                }
                catch
                {
                    user.Password = "unlockmagenta";

                    _magentaDataContext.Entry(user).State = EntityState.Modified;
                    _magentaDataContext.SaveChanges();

                    try
                    {
                        List<Product> products = _magentaDataContext.Products.Where(x => x.Idu == user.Idu)
                                                                      .ToList();
                        foreach (var item in products)
                        {
                            item.Ok = false;
                            item.count = 0;

                            _magentaDataContext.Entry(item).State = EntityState.Modified;
                            _magentaDataContext.SaveChanges();

                        }
                    }
                    catch { }
                }

                return RedirectToAction("Dealers_Reviews");
            }
            else
            {
                return RedirectToAction("My_Buy", "Bays", new { @id = id });
            }
        }

        public ActionResult All_Customer()
        {
            List<User> users = _magentaDataContext.Users.Where(x => x.Idc == 2 && x.Password != "unlockmagenta")
                                                        .ToList();
            return View(users);
        }

        [HttpPost]
        public ActionResult All_Customer(int id, string but)
        {
            if (but == "delete")
            {
                User user = GetUserByID(id);

                try
                {
                    _magentaDataContext.Users.Remove(user);
                    _magentaDataContext.SaveChanges();

                    return RedirectToAction("All_Customer");
                }
                catch
                {
                    user.Password = "unlockmagenta";

                    _magentaDataContext.Entry(user).State = EntityState.Modified;
                    _magentaDataContext.SaveChanges();

                    return RedirectToAction("All_Customer");
                }

            }
            else
            {
                return RedirectToAction("My_Buy", "Bays", new { @id = id });
            }

        }
    }
}

Magenta_S/Magenta_S/Views/ConrolPanelD/All_Customer.cshtml
@model IEnumerable<Magenta_S.Models.User>

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  
    <link href="~/Content/Dealers_Reviews/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/AllCustomer/theme.لائحة الزبائن.css" rel="stylesheet" />
    <link href="~/Content/AllCustomer/style.لائحة الزبائن.css" rel="stylesheet" />

    <style>
        .container-a
        {
            margin-left:40px;
                width: 100%;
    overflow: hidden;
    background-color:#fff;
        }
        h3{
            margin:10px 40px;
        }
            .bu {
            margin-left:10px;
            margin-top:10px;
      
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar ma" href='@Url.Action("HomeAdmin", "Home")'>MAGENTA</a>
            <a href='@Url.Action("Requist", "Requist")' title="Requists" class="icon1">
                <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                    <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z" />
                </svg>
            </a>
            <div class="collapse navbar-collapse">


                <form class="d-flex ">
                    <button class="btn btn-outline-success bu" type="submit">SEARCH</button>
                    <input class="form-control me-2 in" type="search" placeholder="" aria-label="Search">

                </form>


            </div>
        </div>
    </nav>
                    
    
    <div class="row">


        @foreach (var i in Model)
            {
                using (Html.BeginForm(new { @id = i.Idu }))
                {
                <div class="container-a ">
                    <div class="col4 col-lg">
                        <div class="container-b ">
                            <div class="container-1 ">
                                <div class="imag">
                                    <svg class="svg" id="457bf273-24a3-4fd8-a857-e9b918267d6a" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 698 698">
                                        <defs>
                                            <linearGradient id="b247946c-c62f-4d08-994a-4c3d64e1e98f" x1="349" y1="698" x2="349" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="gray" stop-opacity="0.25" /><stop offset="0.54" stop-color="gray" stop-opacity="0.12" /><stop offset="1" stop-color="gray" stop-opacity="0.1" /></linearGradient>
                                        </defs>
                                        <title>profile pic</title>
                                        <g opacity="0.5"><circle cx="349" cy="349" r="349" fill="url(#b247946c-c62f-4d08-994a-4c3d64e1e98f)" /></g>
                                        <circle cx="349.68" cy="346.77" r="341.64" fill="#f5f5f5" />
                                        <path d="M601,790.76a340,340,0,0,0,187.79-56.2c-12.59-68.8-60.5-72.72-60.5-72.72H464.09s-45.21,3.71-59.33,67A340.07,340.07,0,0,0,601,790.76Z" transform="translate(-251 -101)" fill="#00b0ff" />
                                        <circle cx="346.37" cy="339.57" r="164.9" fill="#333" />
                                        <path d="M293.15,476.92H398.81a0,0,0,0,1,0,0v84.53A52.83,52.83,0,0,1,346,614.28h0a52.83,52.83,0,0,1-52.83-52.83V476.92a0,0,0,0,1,0,0Z" opacity="0.1" />
                                        <path d="M296.5,473h99a3.35,3.35,0,0,1,3.35,3.35v81.18A52.83,52.83,0,0,1,346,610.37h0a52.83,52.83,0,0,1-52.83-52.83V476.35A3.35,3.35,0,0,1,296.5,473Z" fill="#fdb797" />
                                        <path d="M544.34,617.82a152.07,152.07,0,0,0,105.66.29v-13H544.34Z" transform="translate(-251 -101)" opacity="0.1" />
                                        <circle cx="346.37" cy="372.44" r="151.45" fill="#fdb797" />
                                        <path d="M489.49,335.68S553.32,465.24,733.37,390l-41.92-65.73-74.31-26.67Z" transform="translate(-251 -101)" opacity="0.1" />
                                        <path d="M489.49,333.78s63.83,129.56,243.88,54.3l-41.92-65.73-74.31-26.67Z" transform="translate(-251 -101)" fill="#333" />
                                        <path d="M488.93,325a87.49,87.49,0,0,1,21.69-35.27c29.79-29.45,78.63-35.66,103.68-69.24,6,9.32,1.36,23.65-9,27.65,24-.16,51.81-2.26,65.38-22a44.89,44.89,0,0,1-7.57,47.4c21.27,1,44,15.4,45.34,36.65.92,14.16-8,27.56-19.59,35.68s-25.71,11.85-39.56,14.9C608.86,369.7,462.54,407.07,488.93,325Z" transform="translate(-251 -101)" fill="#333" />
                                        <ellipse cx="194.86" cy="372.3" rx="14.09" ry="26.42" fill="#fdb797" />
                                        <ellipse cx="497.8" cy="372.3" rx="14.09" ry="26.42" fill="#fdb797" />
                                    </svg>
                                </div>
                                <h2>@Html.DisplayFor(x => i.Fname) @Html.DisplayFor(x => i.Lname) </h2>
                                <h3>@Html.DisplayFor(x => i.Hiredate)</h3>
                            </div>
                            <div class="container-2">
                                <div class="inn">
                                    <div class="label">
                                        <label>Name :</label><p>@Html.DisplayFor(x => i.Fname) @Html.DisplayFor(x => i.Lname)</p>
                                    </div>
                                    <div class="label">
                                        <label>Email :</label><p>@Html.DisplayFor(x => i.Username)</p>
                                    </div>
                                    <div class="label">
                                        <label>phone :</label><p>@Html.DisplayFor(x => i.Phone)</p>
                                    </div>
                                    <div class="label">
                                        <label>Nmuber prodact buy :</label><p>@Html.DisplayFor(x => i.CountProduct)</p>
                                    </div>
                                    <div class="label">
                                        <label>address :</label><p>@Html.DisplayFor(x => i.address)</p>
                                    </div>
                                    <div class="label">
                                        <label>birthday :</label><p>@Html.DisplayFor(x => i.birthday)</p>
                                    </div>
                                    <div class="cold">
                                        <div class="in">
                                            <button type="submit" class="bth n1" name="but" value="prodact">prodact Bay</button>
                                            <button type="submit" class="bth n2" name="but" value="delete">DELETE</button>


                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            }
        }

    </div>



</body>
</html>

Magenta_S/Magenta_S/Views/ConrolPanelD/ConrolPanelD.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link href="~/Content/controlpanel/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/controlpanel/theme.css" rel="stylesheet" />
    <link href="~/Content/controlpanel/style2.css" rel="stylesheet" />

</head>
<body>
    <!-- start nav -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar ma" href='@Url.Action("HomeAdmin", "Home")'>MAGENTA</a>
            <a href='@Url.Action("Requist", "Requist")' title="Requists" class="icon1">
                <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                    <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z" />
                </svg>
            </a>
            <div class="collapse navbar-collapse">


                <form class="d-flex ">
                    <button class="btn btn-outline-success bu" type="submit">SEARCH</button>
                    <input class="form-control me-2 in" type="search" placeholder="" aria-label="Search">

                </form>


            </div>
        </div>
    </nav>
    <!--end nav-->
    <!--

    background-color: #e60023
    background-color: #0072b1
     -->
    <div class="aaa">
        <div class="container">

            <div class="row text-center">

                @*<button onclick="location.href='@Url.Action("Dealers_Reviews","ConrolPanelD")'" class="col-lg-4 btn  " style="background-color: #3b5998">
                        dealers reviews<br>
                        <p>عرض التجار وحذفها</p>
                    </button>*@

                    <button class="col-lg-4 btn " style="background-color: #00acee"  onclick="location.href='@Url.Action("All_Customer","ConrolPanelD")'"   >
                        Customers reviews<br>
                        <p>نصائح لزيادة المبيعات</p>
                    </button>

                  
</div>
        </div>
        <i class="bi bi-archive-fill"></i>

    </div>

    <script src="~/Scripts/controlpanel/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/controlpanel/bootstrap.min.js"></script>
</body>
</html>

Magenta_S/Magenta_S/Views/ConrolPanelD/Dealers_Reviews.cshtml
@model IEnumerable<Magenta_S.Models.User>

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="~/Content/Dealers_Reviews/style.لائحة عرض التجار.css" rel="stylesheet" />
    <link href="~/Content/Dealers_Reviews/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Dealers_Reviews/theme.لائحة عرض التجار.css" rel="stylesheet" />

    <style> 

        .container-a{
    width: 100%;
    overflow: hidden;
    background-color:#fff;
}
            .bu {
            margin-left:10px;
            margin-top:10px;
      
        }
        </style>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar ma" href='@Url.Action("HomeAdmin", "Home")'>MAGENTA</a>
            <a href='@Url.Action("Requist", "Requist")' title="Requists" class="icon1">
                <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                    <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z" />
                </svg>
            </a>
            <div class="collapse navbar-collapse">


                <form class="d-flex ">
                    <button class="btn btn-outline-success bu" type="submit">SEARCH</button>
                    <input class="form-control me-2 in" type="search" placeholder="" aria-label="Search">

                </form>


            </div>
        </div>
    </nav>
    

    <div class="row">
        @foreach (var i in Model)
        {
            using (Html.BeginForm(new {@id=i.Idu }))
            {

                <div class="container-a ">
                    <div class="col4 col-lg">
                        <div class="container-b ">
                            <div class="container-1 ">
                                <div class="imag">
                                    <svg class="svg" id="457bf273-24a3-4fd8-a857-e9b918267d6a" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 698 698">
                                        <defs>
                                            <linearGradient id="b247946c-c62f-4d08-994a-4c3d64e1e98f" x1="349" y1="698" x2="349" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="gray" stop-opacity="0.25" /><stop offset="0.54" stop-color="gray" stop-opacity="0.12" /><stop offset="1" stop-color="gray" stop-opacity="0.1" /></linearGradient>
                                        </defs>
                                        <title>profile pic</title>
                                        <g opacity="0.5"><circle cx="349" cy="349" r="349" fill="url(#b247946c-c62f-4d08-994a-4c3d64e1e98f)" /></g>
                                        <circle cx="349.68" cy="346.77" r="341.64" fill="#f5f5f5" />
                                        <path d="M601,790.76a340,340,0,0,0,187.79-56.2c-12.59-68.8-60.5-72.72-60.5-72.72H464.09s-45.21,3.71-59.33,67A340.07,340.07,0,0,0,601,790.76Z" transform="translate(-251 -101)" fill="#00b0ff" />
                                        <circle cx="346.37" cy="339.57" r="164.9" fill="#333" />
                                        <path d="M293.15,476.92H398.81a0,0,0,0,1,0,0v84.53A52.83,52.83,0,0,1,346,614.28h0a52.83,52.83,0,0,1-52.83-52.83V476.92a0,0,0,0,1,0,0Z" opacity="0.1" />
                                        <path d="M296.5,473h99a3.35,3.35,0,0,1,3.35,3.35v81.18A52.83,52.83,0,0,1,346,610.37h0a52.83,52.83,0,0,1-52.83-52.83V476.35A3.35,3.35,0,0,1,296.5,473Z" fill="#fdb797" />
                                        <path d="M544.34,617.82a152.07,152.07,0,0,0,105.66.29v-13H544.34Z" transform="translate(-251 -101)" opacity="0.1" />
                                        <circle cx="346.37" cy="372.44" r="151.45" fill="#fdb797" />
                                        <path d="M489.49,335.68S553.32,465.24,733.37,390l-41.92-65.73-74.31-26.67Z" transform="translate(-251 -101)" opacity="0.1" />
                                        <path d="M489.49,333.78s63.83,129.56,243.88,54.3l-41.92-65.73-74.31-26.67Z" transform="translate(-251 -101)" fill="#333" />
                                        <path d="M488.93,325a87.49,87.49,0,0,1,21.69-35.27c29.79-29.45,78.63-35.66,103.68-69.24,6,9.32,1.36,23.65-9,27.65,24-.16,51.81-2.26,65.38-22a44.89,44.89,0,0,1-7.57,47.4c21.27,1,44,15.4,45.34,36.65.92,14.16-8,27.56-19.59,35.68s-25.71,11.85-39.56,14.9C608.86,369.7,462.54,407.07,488.93,325Z" transform="translate(-251 -101)" fill="#333" />
                                        <ellipse cx="194.86" cy="372.3" rx="14.09" ry="26.42" fill="#fdb797" />
                                        <ellipse cx="497.8" cy="372.3" rx="14.09" ry="26.42" fill="#fdb797" />
                                    </svg>
                                </div>
                                <h2> @Html.DisplayFor(x => i.Fname) @Html.DisplayFor(x => i.Lname)</h2>
                                <label style="font-size:30px;margin-left:40px;color:#ccc">@Html.DisplayFor(x => i.Hiredate))</label>
                            </div>
                            <div class="container-2">
                                <div class="inn">

                                    <div class="label">
                                        <label>Name :</label><p>@Html.DisplayFor(x => i.Fname) @Html.DisplayFor(x => i.Lname)</p>
                                    </div>
                                    <div class="label">
                                        <label>Email :</label><p> @Html.DisplayFor(x => i.Username) </p>
                                    </div>
                                    <div class="label">
                                        <label>phone :</label><p>@Html.DisplayFor(x => i.Phone)</p>
                                    </div>
                                    <div class="label">
                                        <label>Coomirical-register :</label><p>@Html.DisplayFor(x => i.CommercialRecord)</p>
                                    </div>
                                    <div class="label">
                                        <label>Nmuber prodact add :</label><p>@Html.DisplayFor(x => i.CountProduct)</p>
                                    </div>
                                    <div class="label">
                                        <label>address :</label><p>@Html.DisplayFor(x => i.address)</p>
                                    </div>
                                    <div class="label">
                                        <label>birthday :</label><p>@Html.DisplayFor(x => i.birthday)</p>
                                    </div>

                                    <div class="cold">
                                        <div class="in">
                                            @*formaction="Dealers_Delete onclick="*@

                                            <input type="submit" class="bth n1" name="but" value="delete"  />
                                            <input type="submit" class="bth n2" value="product" name="but">



                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>

</body>
</html>